services:
  app:
    build: .
    depends_on:
      database:
        condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - .:/app
    env_file:
      - app.env
    ports:
      - 8000:8000

  database:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - db.env
    volumes:
      - db_vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 5

volumes:
  db_vol: