# Generated by Django 5.1.2 on 2024-10-26 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The title of your password to describe what it is.', max_length=255)),
                ('username', models.CharField(blank=True, help_text='The username for your password.', max_length=255)),
                ('password', models.CharField(blank=True, help_text='This is your password you want to store.', max_length=255)),
                ('uri', models.URLField(blank=True, help_text='This is the website or application for your password.')),
                ('note', models.CharField(blank=True, help_text='This is any notes for your password. Keep it short!', max_length=255)),
                ('folder', models.ForeignKey(blank=True, help_text='Select one of your folders to categorize the password, or select none.', on_delete=django.db.models.deletion.CASCADE, to='painlessapp.folder')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
