# Generated by Django 5.1.2 on 2024-11-18 03:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painlessapp', '0003_passkey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'user_id')},
        ),
    ]
