# Generated by Django 5.1.1 on 2024-12-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painlessapp', '0006_folder_created_at_folder_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userpass',
            name='name',
            field=models.CharField(help_text='The title of your password to describe what it is.', max_length=100),
        ),
        migrations.AlterField(
            model_name='userpass',
            name='username',
            field=models.CharField(blank=True, help_text='The username for your password.', max_length=100),
        ),
    ]
